# Generated by Django 6.0.4 on 2026-04-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('road', 'Road & Potholes'), ('water', 'Water Supply'), ('garbage', 'Garbage & Waste'), ('drainage', 'Drainage & Sewage'), ('streetlight', 'Street Lighting'), ('park', 'Parks & Public Spaces'), ('encroach', 'Encroachment'), ('noise', 'Noise Pollution'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='complaint',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
