# Generated by Django 6.0.4 on 2026-04-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_category_complaint_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
